#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "my_capsule"
name = "my_capsule"
description.en = "Custom Gemini capsule with SFTP access and HtmGem"
description.fr = "Capsule Gemini personnalisée avec accès SFTP et HtmGem"

version = "v1.4.1~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
demo = "https://gmi.sbgodin.fr/htmgem/"
code = "https://tildegit.org/Sbgodin/htmgem"
website = "https://tildegit.org/Sbgodin/htmgem"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

    [install.with_sftp]
    ask.en = "Do you need a SFTP access?"
    ask.fr = "Avez-vous besoin d'un accès SFTP ?"
    type = "boolean"
    default = true

    [install.with_mysql]
    ask.en = "Do you need a MySQL database?"
    ask.fr = "Avez-vous besoin d'une base de données MySQL ?"
    type = "boolean"
    default = false

[resources]
    [resources.sources.main]
    url = "https://tildegit.org//Sbgodin/htmgem/archive/v1.4.1.tar.gz"
    sha256 = "4d21fbdf5f89e510052185ea9d331614338353886baaecc05d007fa1481f75ce"
    autoupdate.strategy = "latest_gitea_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.2-fpm",
        "php8.2-mbstring",
    ]
    packages_from_raw_bash = """
        if [[ "$database" == true ]]; then
            echo "mariadb-server, php8.2-mysql"
        fi
    """

    [resources.database]
    # Might not be used, but it's easier to handle it here
    type = "mysql"
