packaging_format = 2

id = "my_capsule"
name = "my_capsule"
description.en = "Custom Gemini capsule with SFTP access and HtmGem to make your Gemini pages reachable on the web."
description.fr = "Capsule Gemini personnalisée avec accès SFTP et HtmGem pour rendre vos pages Gemini accessibles sur le web."

version = "1.4.1~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
demo = "https://gmi.sbgodin.fr/htmgem/"
code = "https://tildegit.org/Sbgodin/htmgem"
website = "https://tildegit.org/Sbgodin/htmgem"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.1.20"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"
    optional = true

    [install.with_sftp]
    ask.en = "Do you need a SFTP access?"
    ask.fr = "Avez-vous besoin d'un accès SFTP ?"
    type = "boolean"
    default = true

    [install.with_mysql]
    ask.en = "Do you need a MySQL database?"
    ask.fr = "Avez-vous besoin d'une base de données MySQL ?"
    type = "boolean"
    default = false

[resources]
        [resources.sources.main]
        url = "https://tildegit.org/sbgodin/HtmGem/archive/v1.4.1.tar.gz"
        sha256 = "c7a1d21f6791f567222a1bfb26d72fd44c6083cddb8536011477cf001eb90d27"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "mysql"
