#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_apps
source /usr/share/yunohost/helpers

#=================================================
# INSTALL GEMSERV
#=================================================
ynh_script_progression "Installing Gemserv..."

ynh_install_apps --apps="gemserv"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Configuring system user..."

if [ "$with_sftp" -eq 1 ]; then
    usermod -a -G "sftp.app" "$app"
fi

if [ -n "$password" ]; then
    # Add the password to this user
    chpasswd <<< "${app}:${password}"
    # By default, passwords are not saved
    ynh_app_setting_set --key=password --value="$password"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/www/htmgem"

chmod o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

# Home directory of the user needs to be owned by $app to allow SFTP connections
chown "$app:$app" "$install_dir"
setfacl -m g:"$app":r-x "$install_dir"
setfacl -m g:"www-data":r-x "$install_dir"
setfacl -m g:"gemserv":r-x "$install_dir"

#=================================================
# BUILD DEFAULT CAPSULE
#=================================================
ynh_script_progression "Building default capsule..."

if [ "$with_sftp" -eq 1 ]; then
    ynh_config_add --template="index.gmi" --destination="$install_dir/www/index.gmi"
else
    ynh_config_add --template="index_no_sftp.gmi" --destination="$install_dir/www/index.gmi"
fi

chmod 644 "$install_dir/www/index.gmi"
chown "$app:$app" "$install_dir/www/index.gmi"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated Gemserv config
_ynh_add_gemserv_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
