#!/bin/bash

source _common.sh
source ynh_apps
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

_ynh_remove_gemserv_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

# Remove metapackage and its dependencies
ynh_remove_apps

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
