#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source ../settings/scripts/ynh_apps
source /usr/share/yunohost/helpers

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_script_progression "Configuring the system user..."

if [ "$with_sftp" -eq 1 ]; then
    usermod -a -G "sftp.app" "$app"
fi

if [ -n "$password" ]; then
    # Add the password to this user
    chpasswd <<< "${app}:${password}"
fi

#=================================================
# INSTALL GEMSERV
#=================================================
ynh_script_progression --message="Installing Gemserv..."

ynh_install_apps --apps="gemserv"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R $app:www-data "$install_dir"

# Home directory of the user needs to be owned by $app to allow
# SFTP connections
chown $app:$app "$install_dir"
setfacl -m g:$app:r-x "$install_dir"
setfacl -m g:www-data:r-x "$install_dir"
setfacl -m g:gemserv:r-x "$install_dir"
chmod o-rwx "$install_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/gemserv/config.d/$domain.toml"
ynh_systemctl --service=gemserv --action=reload

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="php$php_version-fpm" --action=reload

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
